/: raw
/about/why: raw

/wisdom/: section
/virtue/: section
/calm/: section

/wisdom/understanding: waside
/wisdom/intention: waside

/virtue/speech: waside
/virtue/action: waside
/virtue/livelihood: waside

/calm/effort: waside
/calm/mindfulness: waside
/calm/concentration: waside